// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ValidatorInterface is an autogenerated mock type for the ValidatorInterface type
type ValidatorInterface struct {
	mock.Mock
}

// Struct provides a mock function with given fields: s
func (_m *ValidatorInterface) Struct(s interface{}) error {
	ret := _m.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for Struct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewValidatorInterface creates a new instance of ValidatorInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewValidatorInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ValidatorInterface {
	mock := &ValidatorInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
